### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by Petros0** [dmitrij-drandarov/Spring-5-Angular-4-Gradle-Example#5]
Hello, is there the possibility to deploy it as one application?

**Comment by drandarov-io** [comment]
Hi,

running something similar to the following task should result in a Spring-Boot-bootJar including the Angular Frontend:

```
task bootJarFull(type: GradleBuild) {
    group 'application'
    setTasks([':client:npmUpdate', ':client:clean', ':client:buildClientToSpring', ':backend:bootJar'])
}
```

**Comment by Petros0** [comment]
Great.

Works perfectly. Thank you.
