### ISSUE TITLE
Refreshing Page Crashes App in bootFullApplication Mode.

### ISSUE THREAD

**Issue by vtsarkov** [dmitrij-drandarov/Spring-5-Angular-4-Gradle-Example#6]
Hello!

I'm experiencing an issue where refreshing the angular app in the browser when served by Spring Boot 
 through :bootFullApplication shows the default "/error" mapping.

When running the angular app through ng-serve, refreshing the browser page on "http://localhost:4200/dashboard" works.

When serving the angular app through Spring Boot, refreshing the browser page on "http://localhost:8080/dashboard" redirects to Spring's default "/error". 

Presumably because "/dashboard" and that is not a resource exposed through the Spring Boot Controller.

Thank you!

**Comment by drandarov-io** [comment]
Hi,
this doesn't seem to be a trivial issue. As I don't have time right now to evaluate / fix it myself: If you find this mistake, please create a pull request and I can merge it.

**Comment by mariusreusch** [comment]
Hi, I created a pull request. The solution requires the configurations of all angular routes in a backend controller, but it would enable page refresh.

**Comment by drandarov-io** [comment]
Thanks a lot! :)
